// Scans all SKILL.md files under skills/, parses frontmatter, writes skills-data.js and patches index.html.
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildInlineJsonMarkerBlock,
  buildSkillsPayload,
  buildSkillRecords,
} from "./docs-data-shared.ts";
import {
  patchDocsIndexPngBranding,
  replaceBetweenMarkerPair,
} from "./docs-index-png-branding.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const SKILLS_ROOT = join(REPO_ROOT, "skills");
const OUT_FILE = join(REPO_ROOT, "skills-data.js");
const CATALOG_JSON = join(REPO_ROOT, "skill-catalog.json");
const INDEX_FILE = join(REPO_ROOT, "index.html");

const INDEX_SKILLS_BEGIN = "<!-- jstack:generated-skills-data -->";
const INDEX_SKILLS_END = "<!-- /jstack:generated-skills-data -->";

async function main(): Promise<void> {
  const records = await buildSkillRecords(REPO_ROOT, SKILLS_ROOT);
  const payload = buildSkillsPayload(records);

  const payloadJson = JSON.stringify(payload);
  /** Prevent `</script>` or `<` sequences inside JSON from breaking HTML parsing. */
  const payloadJsonForInlineScript = payloadJson.replaceAll("<", "\\u003c");

  const js = `/* eslint-disable */
// Generated by scripts/generate-docs-data.ts — do not edit by hand.
// Regenerate: bun run docs:generate
window.__JSTACK_SKILLS__ = ${payloadJson};
`;

  await writeFile(OUT_FILE, js, "utf8");
  console.log(`Wrote ${OUT_FILE} (${records.length} skills)`);

  const catalogBody = {
    generatedAt: payload.generatedAt,
    count: payload.count,
    skills: records,
  };
  await writeFile(
    CATALOG_JSON,
    `${JSON.stringify(catalogBody, null, 2)}\n`,
    "utf8",
  );
  console.log(`Wrote ${CATALOG_JSON}`);

  const indexHtml = await readFile(INDEX_FILE, "utf8");
  const innerBetweenMarkers =
    "\n" +
    buildInlineJsonMarkerBlock([
      {
        scriptId: "jstack-skills-payload",
        globalName: "__JSTACK_SKILLS__",
        varName: "payload",
        json: payloadJsonForInlineScript,
      },
    ]) +
    "\n";
  const nextHtml = await patchDocsIndexPngBranding(
    replaceBetweenMarkerPair(
      indexHtml,
      INDEX_SKILLS_BEGIN,
      INDEX_SKILLS_END,
      innerBetweenMarkers,
    ),
    REPO_ROOT,
  );
  await writeFile(INDEX_FILE, nextHtml, "utf8");
  console.log(
    `Patched ${INDEX_FILE} inline skills payload (${records.length} skills)`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
