// Scans all SKILL.md files under skills/, parses frontmatter, writes skills-data.js and patches index.html.
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildSkillsPayload,
  buildSkillRecords,
} from "./docs-data-shared.ts";
import { patchDocsIndexPngBranding } from "./docs-index-png-branding.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const SKILLS_ROOT = join(REPO_ROOT, "skills");
const OUT_FILE = join(REPO_ROOT, "skills-data.js");
const CATALOG_JSON = join(REPO_ROOT, "skill-catalog.json");
const INDEX_FILE = join(REPO_ROOT, "index.html");

const INDEX_SKILLS_BEGIN = "<!-- jstack:generated-skills-data -->";
const INDEX_SKILLS_END = "<!-- /jstack:generated-skills-data -->";

async function main(): Promise<void> {
  const records = await buildSkillRecords(REPO_ROOT, SKILLS_ROOT);
  const payload = buildSkillsPayload(records);

  const payloadJson = JSON.stringify(payload);
  /** Prevent `</script>` or `<` sequences inside JSON from breaking HTML parsing. */
  const payloadJsonForInlineScript = payloadJson.replaceAll("<", "\\u003c");

  const js = `/* eslint-disable */
// Generated by scripts/generate-docs-data.ts — do not edit by hand.
// Regenerate: bun run docs:generate
window.__JSTACK_SKILLS__ = ${payloadJson};
`;

  await writeFile(OUT_FILE, js, "utf8");
  console.log(`Wrote ${OUT_FILE} (${records.length} skills)`);

  const catalogBody = {
    generatedAt: payload.generatedAt,
    count: payload.count,
    skills: records,
  };
  await writeFile(CATALOG_JSON, `${JSON.stringify(catalogBody, null, 2)}\n`, "utf8");
  console.log(`Wrote ${CATALOG_JSON}`);

  const bootstrapScript = [
    "(function () {",
    '  function parseJsonScript(id) {',
    "    var el = document.getElementById(id);",
    "    if (!el) return null;",
    "    try {",
    '      return JSON.parse(el.textContent || "null");',
    "    } catch (e) {",
    "      return null;",
    "    }",
    "  }",
    '  var payload = parseJsonScript("jstack-skills-payload");',
    "  if (payload) window.__JSTACK_SKILLS__ = payload;",
    "})();",
  ].join("\n");
  const indentedBootstrap = bootstrapScript.split("\n").join("\n      ");

  const indexHtml = await readFile(INDEX_FILE, "utf8");
  const i0 = indexHtml.indexOf(INDEX_SKILLS_BEGIN);
  const i1 = indexHtml.indexOf(INDEX_SKILLS_END);
  if (i0 === -1 || i1 === -1 || i1 < i0) {
    throw new Error(
      `index.html must contain ${INDEX_SKILLS_BEGIN} and ${INDEX_SKILLS_END} in order (run docs:generate after adding markers).`,
    );
  }
  const i1End = i1 + INDEX_SKILLS_END.length;
  const newBlock = [
    INDEX_SKILLS_BEGIN,
    `    <script type="application/json" id="jstack-skills-payload">${payloadJsonForInlineScript}</script>`,
    "    <script>",
    `      ${indentedBootstrap}`,
    "    </script>",
    INDEX_SKILLS_END,
  ].join("\n");
  const nextHtml = await patchDocsIndexPngBranding(
    indexHtml.slice(0, i0) + newBlock + indexHtml.slice(i1End),
    REPO_ROOT,
  );
  await writeFile(INDEX_FILE, nextHtml, "utf8");
  console.log(`Patched ${INDEX_FILE} inline skills payload (${records.length} skills)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
