#!/usr/bin/env bun
/**
 * Skill quality gate — the counterpart to `agents-depth-check.ts`.
 *
 * Depth is enforced PROPORTIONALLY to judgment load, using each skill's own `effort`
 * frontmatter as the tier signal. A lookup skill (`jira/get`, `effort: low`) legitimately
 * needs no threshold table; a skill that renders a verdict (`research/competitive`,
 * `effort: max`) does. Demanding the same depth everywhere would just manufacture filler,
 * which is the failure mode this repo has been removing.
 *
 *   CORRECTNESS (always fatal) — baseline structure every skill must have, plus a ban on
 *   the generic template lines that used to occupy 122 skills while changing no behavior.
 *
 *   DEPTH (advisory by default, fatal under --strict) — tier-appropriate signals.
 *
 * Most skill bodies are GENERATED by `scripts/apply_detailed_skills.py`. The durable way to
 * satisfy a depth finding is therefore usually to add a per-key entry under
 * `scripts/skill_deep/` (merged into `CATEGORY_DEEP`), not to hand-edit the SKILL.md —
 * a hand edit to a non-SKIP skill is lost on the next regeneration.
 */
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseYamlFrontmatter } from "./lib/parse-frontmatter.js";
import { discoverAllSkillRelativePaths } from "../evals/discover.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const skillsRoot = join(root, "skills");
const strict = process.argv.includes("--strict");
const asJson = process.argv.includes("--json");

type Tier = "A" | "B" | "C";

/** `effort` encodes how much judgment a skill exercises, so it doubles as the depth tier. */
const TIER_BY_EFFORT: Record<string, Tier> = {
  max: "A",
  xhigh: "A",
  high: "A",
  medium: "B",
  low: "C",
};

/** Generic template prose that shipped in >100 skills and named no tool, path, or check. */
const DEAD_BOILERPLATE = [
  "Prefer read-only first, then idempotent updates, then irreversible changes",
  "Correct surface, no stray side effects, tone matches",
];

const FICTION = [
  /\bAcme\b/,
  /\bContoso\b/,
  /\bCompetitor X\b/,
  /SOC2 audit in \w+/i,
];

interface Rule {
  id: string;
  minTier: Tier;
  test: (body: string) => boolean;
  hint: string;
}

const TIER_ORDER: Record<Tier, number> = { A: 3, B: 2, C: 1 };
const appliesTo = (rule: Rule, tier: Tier) =>
  TIER_ORDER[tier] >= TIER_ORDER[rule.minTier];

const RULES: Rule[] = [
  {
    id: "domain-rules",
    minTier: "B",
    // Was keyword-literal on "Domain rules", which failed skills that state the same content
    // under an equivalent heading ("Hard rules", "Absolute rules"). Accepting synonyms adds
    // only one skill and still leaves the rule discriminating, so it is not a loophole.
    test: (b) =>
      /^##+ .*(Domain rules|Hard rules|Absolute rules|Prime Directives)/m.test(
        b,
      ),
    hint: "no domain-rules section — add a skill_deep/CATEGORY_DEEP entry stating rules specific to this domain (a 'Hard rules' or 'Absolute rules' heading also counts)",
  },
  {
    id: "thresholds",
    minTier: "A",
    // "Applicable criteria" rather than strictly numbers. Two earlier versions of this rule
    // were wrong in opposite directions: the unit vocabulary omitted domain units like LOC
    // (so "200-400 LOC" went uncounted), and `min\b` failed on "minutes" because a word
    // character follows. Separately, some Tier A skills are irreducibly qualitative — for an
    // announcement review the binding constraints are ordering and approval gates, not
    // numbers. A gating/decision-criteria table is the qualitative equivalent of a threshold
    // and is equally checkable, so it satisfies the rule.
    test: (b) => {
      const units =
        b.match(
          /\b\d+(?:[.,]\d+)?\s*(?:%|:1|×|x\b|ms\b|sec|min|hour|hr\b|day|week|month|kb|mb|gb|px|loc\b|line|row|item|node|reviewer|approver|comment|pr\b|attempt|step|worker|point|char|s\b)/gi,
        ) ?? [];
      const cmps = b.match(/[<>≤≥]=?\s*\d+/g) ?? [];
      if (units.length + cmps.length >= 3) return true;

      // Qualitative fallback: an explicit verdict/gate criteria table.
      const hasCriteriaTable =
        /^\|.*\|/m.test(b) &&
        /(approve|revise|block|gate|sign-?off|before send|criteri)/i.test(b) &&
        /(threshold|criteri|gate|verdict)/i.test(b);
      return hasCriteriaTable;
    },
    hint: "no applicable criteria — state thresholds a reader can adjudicate against, or an explicit approve/revise/block (or gating) criteria table if the domain is qualitative",
  },
  {
    id: "anti-patterns",
    minTier: "A",
    // Substring presence alone was too weak: prose merely mentioning "anti-pattern" passed
    // without ever naming one. Require a heading AND a table beneath it, since the value is
    // in the enumerated rows (anti-pattern | why wrong | what instead), not the word.
    test: (b) => {
      // The label may be a heading (`## Named anti-patterns`) or an emphasized list item
      // (`3. **Anti-patterns**`) — both are used in this repo. What matters is that an
      // enumerated table follows, not which markup introduces it.
      const m = b.match(
        /^(?:##+ .*anti-?pattern|\s*\d*\.?\s*\*\*anti-?pattern)/im,
      );
      if (!m || m.index === undefined) return false;
      const after = b.slice(m.index, m.index + 1200);
      const rows = after.match(/^\|.*\|.*\|/gm) ?? [];
      return rows.length >= 2; // header row + at least one real entry
    },
    hint: "no named anti-patterns table — add a section with rows of anti-pattern | why wrong | what to do instead",
  },
  {
    id: "worked-example",
    minTier: "A",
    test: (b) =>
      /^##+ .*(Worked example|Example)/im.test(b) &&
      /(weak|bad|vague|before)\b[\s\S]{0,2000}?(sharp|good|better|after)\b/i.test(
        b,
      ),
    hint: "no worked example contrasting a weak output with a sharp one",
  },
  {
    id: "scope-edge",
    minTier: "B",
    test: (b) => /out of scope|must not|does not own|not for\b/i.test(b),
    hint: "no explicit scope edge — state what this skill must NOT do so it doesn't overreach",
  },
];

interface Finding {
  skill: string;
  kind: "correctness" | "depth";
  id: string;
  message: string;
}

/**
 * Explicit, reasoned exemptions from a single depth rule.
 *
 * Preferred over loosening a rule globally: an exemption is visible in the output, carries
 * a justification, and only waives the one rule named. Adding an entry here is a reviewable
 * claim that the rule genuinely does not apply to that skill's shape — not a way to turn a
 * number green. Keep this list short; if it grows, the rule itself is probably wrong.
 */
const EXEMPTIONS: Record<string, Record<string, string>> = {
  "computer-use/cua": {
    thresholds:
      "Command-dispatch/reference skill: its decisions are captured by the 'Choose your tool' and routing tables, not by numeric limits or an approve/revise gate. A threshold table here would be cosmetic.",
  },
};

const findings: Finding[] = [];
const exempted: { skill: string; id: string; reason: string }[] = [];
const tiers = new Map<string, Tier>();
const scores = new Map<string, { passed: number; total: number }>();

const skillDirs = discoverAllSkillRelativePaths(skillsRoot);
for (const rel of skillDirs) {
  const dir = join(skillsRoot, rel);
  const raw = readFileSync(join(dir, "SKILL.md"), "utf8");
  const parsed = parseYamlFrontmatter(raw);
  if (parsed.error && parsed.frontmatterText === undefined) {
    // No `---` delimiters at all — there is no frontmatter text to fall back to parsing.
    findings.push({
      skill: rel,
      kind: "correctness",
      id: "frontmatter",
      message: "missing YAML frontmatter",
    });
    continue;
  }
  const body = parsed.body;

  let meta: Record<string, unknown> = parsed.meta;
  if (parsed.error) {
    // Frontmatter MUST be valid YAML. 27 of 137 files once failed `yaml.safe_load` — usually a
    // colon-space inside an unquoted description — and every consumer using a real YAML parser saw an
    // EMPTY mapping for them, so `name`, `effort`, and `disable-model-invocation` all read as absent.
    // `build_frontmatter` now quotes values via `yaml_scalar()`, so a failure here means either a
    // hand-maintained (SKIP) file or a regression in the quoter. This used to fall back silently to a
    // line-based parse, which hid the problem for as long as it existed.
    findings.push({
      skill: rel,
      kind: "correctness",
      id: "invalid-yaml-frontmatter",
      message:
        `frontmatter is not valid YAML (${parsed.error.split("\n")[0].slice(0, 90)}). ` +
        `Quote any value containing ": " — a consumer using a real YAML parser reads this file's ` +
        `frontmatter as empty, losing name/effort/disable-model-invocation.`,
    });
    // Still parse line-based so the remaining rules can report on this file too. This is a
    // deliberate, already-fixed regression guard (see comment above) — preserve it, don't
    // remove it even though the initial attempt now goes through the shared parser.
    meta = {};
    for (const line of (parsed.frontmatterText ?? "").split("\n")) {
      const i = line.indexOf(":");
      if (i > 0) meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
    }
  }

  // --- correctness ---
  for (const key of ["name", "description", "effort"]) {
    if (typeof meta[key] !== "string" || String(meta[key]).trim() === "") {
      findings.push({
        skill: rel,
        kind: "correctness",
        id: `missing-${key}`,
        message: `frontmatter must set a non-empty '${key}'`,
      });
    }
  }
  // A frontmatter value that is nothing but a YAML block-scalar indicator means the author wrote
  // `key: >-` with the content on following indented lines, and `read_front_matter` in
  // scripts/apply_detailed_skills.py — which is line-based and keeps only lines containing ":" —
  // dropped that content and round-tripped the bare indicator back into the file. The key then
  // survives as the literal two-character string ">-", which reads as real content and consumes
  // skill-listing budget while saying nothing. `computer-use` shipped in exactly this state.
  const BLOCK_SCALAR_ONLY = new Set([">", ">-", ">+", "|", "|-", "|+"]);
  for (const [key, value] of Object.entries(meta)) {
    if (
      typeof value === "string" &&
      BLOCK_SCALAR_ONLY.has(value.trim().replace(/^["']|["']$/g, ""))
    ) {
      findings.push({
        skill: rel,
        kind: "correctness",
        id: "block-scalar-frontmatter",
        message:
          `frontmatter '${key}' is the bare block-scalar indicator "${value.trim()}" — its content was ` +
          `lost by the line-based reader in scripts/apply_detailed_skills.py. Rewrite it as an inline ` +
          `scalar on one line, or move the text into WHEN_TO_USE/DESCRIPTIONS in ` +
          `scripts/apply_detailed_skills_data.py.`,
      });
    }
  }
  for (const dead of DEAD_BOILERPLATE) {
    if (body.includes(dead)) {
      findings.push({
        skill: rel,
        kind: "correctness",
        id: "dead-boilerplate",
        message: `contains generic template prose that names no tool/path/check: "${dead.slice(0, 48)}…" — replace via scripts/apply_detailed_skills_data.py`,
      });
    }
  }
  // Fiction detection must distinguish an ASSERTION from a PLACEHOLDER. The original defect
  // was prose asserting "Competitor X shipped AI features in Q1" as a fact about the reader's
  // market. The same token inside a quoted illustration — «"Competitor X is the market leader"
  // is a claim; "…3x the category median as of <date>" is evidence» — is correct teaching
  // content. Skip lines that are visibly illustrative; flag bare assertions.
  const ILLUSTRATIVE =
    /["“”']|\be\.?g\.?\b|\bfor example\b|\bexample\b|\bplaceholder\b|\bweak\b|\bsharp\b|\bis a claim\b|<[a-z-]+>/i;
  for (const line of body.split("\n")) {
    if (ILLUSTRATIVE.test(line)) continue;
    for (const pattern of FICTION) {
      const hit = line.match(pattern);
      if (hit) {
        findings.push({
          skill: rel,
          kind: "correctness",
          id: "fiction",
          message: `asserts fabricated organization data "${hit[0]}" outside an illustrative example`,
        });
      }
    }
  }

  // --- depth, scaled by tier ---
  const effort = String(meta.effort ?? "low").trim();
  const tier = TIER_BY_EFFORT[effort] ?? "C";
  tiers.set(rel, tier);
  const applicable = RULES.filter((r) => appliesTo(r, tier));
  let passed = 0;
  for (const rule of applicable) {
    if (rule.test(body)) {
      passed++;
      continue;
    }
    const reason = EXEMPTIONS[rel]?.[rule.id];
    if (reason) {
      passed++; // counted as met, but surfaced below so the waiver stays visible
      exempted.push({ skill: rel, id: rule.id, reason });
      continue;
    }
    findings.push({
      skill: rel,
      kind: "depth",
      id: rule.id,
      message: rule.hint,
    });
  }
  scores.set(rel, { passed, total: applicable.length });
}

const correctness = findings.filter((f) => f.kind === "correctness");
const depth = findings.filter((f) => f.kind === "depth");
const byTier = (t: Tier) => [...tiers.entries()].filter(([, v]) => v === t);
const fullyMet = (t: Tier) =>
  byTier(t).filter(([k]) => {
    const s = scores.get(k);
    return s && s.passed === s.total;
  }).length;

if (asJson) {
  console.log(
    JSON.stringify(
      {
        skills: skillDirs.length,
        correctness_errors: correctness.length,
        depth_warnings: depth.length,
        exempted,
        tiers: {
          A: byTier("A").length,
          B: byTier("B").length,
          C: byTier("C").length,
        },
        fully_meeting_tier: {
          A: fullyMet("A"),
          B: fullyMet("B"),
          C: fullyMet("C"),
        },
        findings,
      },
      null,
      2,
    ),
  );
} else {
  if (correctness.length) {
    console.log(`\nCORRECTNESS (${correctness.length}) — always fatal`);
    for (const f of correctness)
      console.log(`  ${f.skill}\n    [${f.id}] ${f.message}`);
  }
  if (depth.length) {
    console.log(
      `\nDEPTH (${depth.length}) — ${strict ? "fatal" : "advisory"}; tier from 'effort'`,
    );
    const worst = [...scores.entries()]
      .filter(([, s]) => s.passed < s.total)
      .sort((a, b) => a[1].passed - b[1].passed)
      .slice(0, 12);
    for (const [skill, s] of worst) {
      const ids = depth
        .filter((f) => f.skill === skill)
        .map((f) => f.id)
        .join(", ");
      console.log(
        `  tier ${tiers.get(skill)}  ${s.passed}/${s.total}  ${skill}  [${ids}]`,
      );
    }
    if (depth.length > 0) {
      const remaining = [...scores.values()].filter(
        (s) => s.passed < s.total,
      ).length;
      if (remaining > worst.length)
        console.log(
          `  … and ${remaining - worst.length} more skills below tier`,
        );
    }
  }
  if (exempted.length) {
    console.log(
      `\nEXEMPTED (${exempted.length}) — rule waived with a stated reason, counted as met`,
    );
    for (const e of exempted)
      console.log(`  ${e.skill} [${e.id}]\n    ${e.reason}`);
  }
  for (const t of ["A", "B", "C"] as Tier[]) {
    const n = byTier(t).length;
    if (n)
      console.log(
        `\nTier ${t}: ${fullyMet(t)}/${n} skills fully meet their tier`,
      );
  }
}

const fatal = correctness.length > 0 || (strict && depth.length > 0);
const summary = `skills-depth-check ${fatal ? "FAILED" : "OK"} (${skillDirs.length} skills; ${correctness.length} correctness, ${depth.length} depth)${strict || fatal ? "" : " — run with --strict to enforce depth"}`;
if (fatal) {
  console.error(asJson ? summary : `\n${summary}`);
  process.exit(1);
}
if (asJson) console.error(summary);
else console.log(`\n${summary}`);
