"""
Deep domain content for research, engineering-health/silo, and team-metrics skills.

Owns exactly: research/competitive, research/spike, research/user, engineering/health,
engineering/silo-scan, metrics/team-metrics. See `scripts/skill_deep/__init__.py` for how
this merges into CATEGORY_DEEP (key-first, then category default).
"""
from __future__ import annotations

DEEP: dict[str, str] = {
    "research/competitive": (
        "## Domain rules — competitive research\n"
        "\n"
        "### Absolute rules\n"
        "1. No claim without a source and an as-of date. An undated competitive claim is unusable — pricing, "
        "feature sets, and positioning all decay within a quarter, and a reader cannot tell whether an undated "
        "claim is current or two years stale.\n"
        "2. Rank source quality before citing: **primary** (competitor's own pricing page, product changelog, "
        "SEC filings, job postings, customer contracts) outranks **paid analyst research** (Gartner/Forrester, "
        "dated by report version) which outranks **vendor marketing** (a competitor's — or your own — press "
        "release, which states positioning, not verified capability) which outranks **secondhand aggregator "
        "blogs**. Secondary research is available to every competitor; primary research is what makes a report "
        "intelligence instead of a compiled newspaper clipping ([Contify](https://www.contify.com/resources/blog/reboot-competitive-intelligence-by-leveraging-competitive-intelligence-solution-for-integrating-primary-and-secondary-research/)).\n"
        "3. Separate **claim** from **evidence** in every line: \"the competitor is the market leader\" is a claim; "
        "\"the competitor's G2 review count is 3x the category median as of 2026-06-01\" is evidence. A comparison "
        "table entry with no evidence column is an opinion, not research.\n"
        "4. Disclose the full set of comparison dimensions considered, including ones where the competitor wins. "
        "A table that only shows dimensions favoring one side is cherry-picked even if every cell in it is true.\n"
        "5. Distinguish \"not found\" from \"does not exist.\" Absence of evidence in a search is a coverage gap, "
        "not proof the feature/claim is false — state it as `[not found as of <date>]`.\n"
        "6. Never treat a competitor's marketing copy as proof of a security, compliance, or performance capability. "
        "Marketing states aspiration; verifying the capability needs a doc, a customer reference, or an independent "
        "audit artifact.\n"
        "\n"
        "### Thresholds\n"
        "| Signal | Threshold | Why |\n"
        "|---|---|---|\n"
        "| Pricing/feature claim recency | stale if unchecked >90 days | Public pricing/feature pages change on product-cycle timelines. |\n"
        "| Funding/headcount claim recency | stale if unchecked >180 days | LinkedIn/Crunchbase-style data lags real changes by months. |\n"
        "| Analyst report age | usable <12 months; else label historical | Analyst quadrant/wave placements shift on an annual cadence. |\n"
        "| UI/product-behavior screenshot | stale if >30 days old | Live product changes faster than marketing collateral; verify against the current product, not a cached image. |\n"
        "| Corroboration for a \"materially disadvantages us\" claim | ≥2 independent sources | A single source driving a high-stakes claim is a single point of failure in the brief. |\n"
        "\n"
        "### Named anti-patterns\n"
        "| Anti-pattern | Why wrong | What instead |\n"
        "|---|---|---|\n"
        "| Citing vendor marketing as a verified capability | Marketing states positioning/aspiration, not audited fact | Require a doc, customer reference, or independent audit before treating it as capability |\n"
        "| Feature-checklist theater | A landing page mentioning a word is not proof the mechanism works to spec | Verify via demo, documentation, or trial account before checking the box |\n"
        "| Cherry-picked comparison table | Shows only dimensions that flatter one side, misleading the decision-maker | Disclose the full dimension set considered, including unfavorable ones |\n"
        "| \"Not found\" reported as \"does not exist\" | Absence of evidence isn't evidence of absence | Label `[not found as of <date>]` and flag as a coverage gap, not a negative finding |\n"
        "| Analyst placement cited without report year | Placements move yearly; an undated citation implies false currency | Always cite the specific report edition/year |\n"
        "\n"
        "### Worked example\n"
        "- **Weak:** \"Competitor Y is cheaper than us.\"\n"
        "- **Sharp:** \"Competitor Y's published self-serve tier starts at $X/seat/month (source: Y's pricing page, "
        "checked 2026-07-20) versus our $Z. Y's enterprise tier has no public list price — quote-only — so this is "
        "a self-serve-to-self-serve comparison only, not a full price comparison. Treat any enterprise-tier price "
        "delta as `[unverified]` until we get a real quote.\"\n"
        "- The sharp version names the mechanism (which tiers are actually comparable), the evidence (source + "
        "date), and the fix (scope the claim to what's verifiable, flag the rest).\n"
        "\n"
        "### What this skill must not do\n"
        "- Not a substitute for legal or patent counsel — stop at questions for counsel, don't render a legal opinion "
        "on trademark/patent risk.\n"
        "- Not a scraping tool that violates a competitor's terms of service to obtain data.\n"
        "- Not a source of fabricated competitor financials, headcount, or internal roadmap — if it isn't publicly "
        "sourced, it doesn't go in the brief."
    ),
    "research/spike": (
        "## Domain rules — technical spike\n"
        "\n"
        "### Absolute rules\n"
        "1. Every spike opens with exactly one falsifiable question stated before work starts — not \"explore X\" "
        "but \"can X achieve Y within constraint Z, yes or no.\" If the request bundles two unrelated questions, "
        "split it into two spikes.\n"
        "2. The time-box is set before work starts and is immutable once set. Reaching the boundary without an "
        "answer means stop, write up what's known and unknown, and bring it back for an explicit new decision — "
        "never silently extend ([agilekrc](https://agilekrc.com/agile/agile-spike); [Creately](https://creately.com/guides/scrum-spikes/)).\n"
        "3. A spike's deliverable is a **decision-enabling answer with evidence** — a go/no-go plus what was "
        "learned — not working code. Prototype code produced during a spike is disposable by default.\n"
        "4. Spike code never merges to a production branch by continuation. Converting a spike's findings into real "
        "work requires a new, normally-scoped implementation ticket with its own review and test rigor.\n"
        "5. A spike never writes to production systems, migrates real data, or touches a customer-facing path. If "
        "the investigation requires that, it is implementation work wearing a spike's name.\n"
        "6. Report progress at the timebox's midpoint, not only at the end — a spike that goes silent until the "
        "deadline gives the team no chance to re-scope early.\n"
        "\n"
        "### Thresholds\n"
        "| Signal | Threshold | Why |\n"
        "|---|---|---|\n"
        "| Spike duration | 1–3 days typical; escalate past 5 days without an answer | Beyond this, an open-ended spike has become unbilled implementation, not investigation. |\n"
        "| Primary questions per spike | exactly 1 | Two-plus unrelated questions make \"done\" ambiguous and invite scope creep. |\n"
        "| Progress checkpoint | at 50% of elapsed timebox | Catches silent expansion before the deadline, not after. |\n"
        "| Code merged to main from spike branch | 0 lines, without a follow-up ticket + normal review | Prototype code skipped the rigor production code requires. |\n"
        "| Go/no-go criteria defined | before work starts, not at the end | A spike without a stated stop condition can be re-run indefinitely as analysis paralysis. |\n"
        "\n"
        "### Named anti-patterns\n"
        "| Anti-pattern | Why wrong | What instead |\n"
        "|---|---|---|\n"
        "| Open-ended \"investigate X\" spike | No falsifiable question means no way to know when it's done — it expands to fill the sprint | Rewrite as \"can X achieve Y within Z\" before starting |\n"
        "| Silent time-box extension | Erodes the team's ability to plan sprints; this is exactly how a spike becomes unbilled implementation | Stop at the boundary, report status and learnings, request an explicit new time-box |\n"
        "| Spike code merged directly to main | Prototype code bypassed the review/test bar production code needs | Require a new implementation ticket with normal review before merge |\n"
        "| Spike as analysis-paralysis avoidance | Re-running the same investigation because no go/no-go criteria were set | Set stop conditions before the spike starts, not after it stalls |\n"
        "| Two unrelated questions in one spike | \"Done\" becomes ambiguous — one question can be answered while the other drags | Split into separate spikes, each with its own time-box |\n"
        "\n"
        "### Worked example\n"
        "- **Weak:** \"Spend a few days exploring whether we could use library X.\"\n"
        "- **Sharp:** \"2-day spike: can library X parse our current payload format (`fixtures/payload_v3.json`) at "
        "p95 < 50ms without a custom preprocessor? Go: adopt X, file an implementation ticket. No-go: fall back to "
        "the existing parser. Time-box ends Thursday EOD regardless of outcome; if unresolved by then, report what's "
        "known/unknown and ask for an explicit re-scoped follow-up rather than continuing.\"\n"
        "- The sharp version names the question, the measurable pass/fail bar, and the stop behavior — the weak "
        "version has no way to ever be \"done.\"\n"
        "\n"
        "### What this skill must not do\n"
        "- Not a general project-tracking tool for ordinary story work — spikes are for genuine unknowns, not "
        "routine tickets relabeled to skip estimation.\n"
        "- Not a vehicle for building a production feature under cover of \"just investigating.\"\n"
        "- Not a substitute for writing the decision down — a spike produces the input to a decision; recording the "
        "decision itself belongs to an ADR/architecture skill, not here."
    ),
    "research/user": (
        "## Domain rules — user research\n"
        "\n"
        "### Absolute rules\n"
        "1. State the sample size and what it can and cannot support in the same breath as any finding. Five "
        "participants in a qualitative usability test on a homogenous user group typically surface roughly 85% of "
        "usability problems ([Nielsen/Landauer model, NN/g](https://www.nngroup.com/articles/why-you-only-need-to-test-with-5-users/)) "
        "— but that model says nothing about **how many** total users hit each problem. Issue-discovery and "
        "prevalence are different questions requiring different sample sizes.\n"
        "2. Never state a prevalence percentage (\"60% of users struggle with X\") from a qualitative sample. "
        "Quantitative prevalence claims need roughly 20-40+ participants to be statistically meaningful "
        "([NN/g quant guidance](https://www.nngroup.com/articles/5-test-users-qual-quant/)); a 5-person qual study "
        "can tell you a problem exists, not how common it is.\n"
        "3. Avoid leading questions: don't name the UI element before the user does, don't presuppose difficulty "
        "(\"wasn't this confusing?\"), and don't offer the answer inside the question. Ask what was easy or hard, "
        "not whether something specific was hard "
        "([NN/g](https://www.nngroup.com/articles/leading-questions/)).\n"
        "4. Separate what users **said** (self-report, quotes, stated preference) from what they **did** (observed "
        "task success/failure, time-on-task, actual choice) — label each distinctly in synthesis; never blend them "
        "into one narrative.\n"
        "5. Stated preference is not revealed behavior. When both exist, trust the revealed signal: stated-only "
        "preference research has been shown to predict real purchase/adoption behavior far less reliably than "
        "behavioral evidence in comparable studies — treat a stated-only finding as directional, not decision-grade.\n"
        "6. Distinguish frequent (heavy, representative) users from loud (vocal, self-selected) ones. A sample "
        "drawn only from support tickets or forum threads is a loud-user sample, not a representative one, and "
        "should never be reported as \"users think.\"\n"
        "\n"
        "### Thresholds\n"
        "| Signal | Threshold | Why |\n"
        "|---|---|---|\n"
        "| Qualitative issue-discovery | n=5 per homogenous segment (~85% of usability issues found) | Distinct user segments (e.g. admin vs. end user) each need their own round — the model doesn't transfer across segments ([NN/g](https://www.nngroup.com/articles/how-many-test-users/)). |\n"
        "| Quantitative prevalence claim | ~20-40+ participants minimum | Below this, a percentage claim is not statistically supportable. |\n"
        "| Stated- vs revealed-preference gap | trust revealed evidence when they conflict | Stated preference alone has been shown to substantially under-predict real behavior compared to behavioral methods. |\n"
        "| Verbatim quote per theme | ≥1 direct, attributed quote per major theme reported | A theme with no quote is a summarizer's paraphrase, not a finding. |\n"
        "| Segment homogeneity | test each distinct segment separately | The n=5 rule assumes users are using the product in a similar way; heterogenous segments need their own round. |\n"
        "\n"
        "### Named anti-patterns\n"
        "| Anti-pattern | Why wrong | What instead |\n"
        "|---|---|---|\n"
        "| Prevalence claim from n=5 (\"most users think...\") | Conflates qualitative issue-discovery with quantitative prevalence, which needs a much larger sample | Report as \"found in interviews with N users,\" never as a population percentage |\n"
        "| Leading question (\"wasn't this confusing?\") | Presupposes the answer; respondents mirror the interviewer's framing | Ask a neutral open question (\"what was easy or hard about this task?\") |\n"
        "| Treating stated interest as demand | Say-do gap: \"I'd pay for that\" doesn't predict conversion | Corroborate with a behavioral signal — waitlist conversion, usage of an existing proxy, or an A/B test |\n"
        "| Loud-user sampling (support tickets/forum only) | Overrepresents vocal edge cases; the silent majority is unseen | Supplement with usage data or a random sample of the broader base |\n"
        "| Merging \"said\" and \"did\" into one narrative | Hides exactly the cases where self-report contradicts observed behavior — the most useful signal | Keep them in separate labeled sections: Said vs. Did |\n"
        "\n"
        "### Worked example\n"
        "- **Weak:** \"Users don't like the new checkout flow — 4 out of 5 people said it was confusing.\"\n"
        "- **Sharp:** \"In 5 task-based sessions (one homogenous new-customer segment), 4 of 5 participants failed "
        "to find the 'apply discount' control unprompted (observed: avg. 45s of visible searching before giving up "
        "or asking) — that's a usability-issue signal from a small qual sample, not a population prevalence "
        "estimate. Separately, on the SAID layer: when asked afterward, 3 of 5 said they 'liked' the new flow "
        "overall. That say-do gap (liked it / couldn't use it) means we trust the observed failure over the "
        "self-report here. Recommend relocating the discount control and re-testing with a different n=5 cohort "
        "before rolling to 100%.\"\n"
        "- The sharp version names the mechanism (say-do gap), the evidence (observed time-on-task vs. quoted "
        "sentiment), and the fix (targeted re-test, not a full rollout decision from 5 people).\n"
        "\n"
        "### What this skill must not do\n"
        "- Not a substitute for a properly powered quantitative survey when the actual question is \"what "
        "percentage of our users...\"\n"
        "- Not permission-agnostic — respect participant consent and anonymization; never quote or attribute "
        "beyond the granted permission level.\n"
        "- Not a tool for justifying a decision already made — never select quotes to support a predetermined "
        "conclusion."
    ),
    "engineering/health": (
        "## Domain rules — engineering health\n"
        "\n"
        "### Absolute rules\n"
        "1. Report the DORA four keys as independent axes, never collapsed into one composite \"health score.\" "
        "High throughput with high change-failure rate is fragility, not health, and a blended number hides which "
        "axis is actually the problem.\n"
        "2. Every band claim (\"we're High on lead time\") states the metric, the measurement window, and the "
        "threshold used — a band name with no number behind it is unverifiable.\n"
        "3. Report leading indicators (PR review latency, CI flake trend, deploy-frequency trend) alongside lagging "
        "ones (incident count, MTTR, change-failure rate). Lagging indicators only move after damage is already "
        "done; leading indicators are the only ones that give time to intervene.\n"
        "4. Name what a healthy-looking number could be concealing before declaring health. Zero rollbacks can mean "
        "nothing risky shipped (flags off, low-blast-radius changes) rather than nothing going wrong — state which "
        "explanation the evidence actually supports.\n"
        "5. Never scan or report on a repo outside the ones the user or config specified.\n"
        "6. Never rank or name individuals in a health report — this is a team/repo-level rollup, not a performance "
        "review.\n"
        "\n"
        "### Thresholds — DORA four keys\n"
        "Bands per [getdx.com's 2024 DORA benchmark summary](https://getdx.com/blog/dora-metrics/); state which "
        "year's bands you're using, since DORA's own published thresholds shift release to release.\n"
        "\n"
        "| Metric | Elite | High | Medium | Low |\n"
        "|---|---|---|---|---|\n"
        "| Deployment frequency | multiple/day | daily–weekly | weekly–monthly | monthly–biannually |\n"
        "| Lead time for changes | <1 day | 1 day–1 week | 1 week–1 month | 1–6 months |\n"
        "| Change failure rate | 0–15% | 16–30% | 16–30% | 46–60% |\n"
        "| Time to restore (MTTR) | <1 hour | <1 day | 1 day–1 week | 1 week–1 month |\n"
        "\n"
        "Additional practitioner thresholds:\n"
        "\n"
        "| Signal | Threshold | Why |\n"
        "|---|---|---|\n"
        "| CI flake rate | >1% of runs over the last 50 runs | A test that fails 1-in-100 times trains the team to re-run instead of read failures — treat as a leading indicator of eroding trust in the suite, not noise ([Google Testing Blog](https://testing.googleblog.com/2016/05/flaky-tests-at-google-and-how-we.html)). |\n"
        "| PR stale threshold | >3 days open with no review activity | A stale PR queue is a leading indicator of lead-time degradation before it shows up in the DORA number. |\n"
        "| Revert-risk window | merge to main with a failing check or a single reviewer on a critical path | Corroborates change-failure risk before it becomes an incident. |\n"
        "\n"
        "### Named anti-patterns\n"
        "| Anti-pattern | Why wrong | What instead |\n"
        "|---|---|---|\n"
        "| Composite \"health score\" (single 0-100 number) | Hides which axis is the actual problem; a team can raise the score by trading stability for speed (or the reverse) with no one noticing which | Report each DORA axis separately with its band; summarize as \"N of 4 elite/high,\" never a single blended number |\n"
        "| Lagging-only reporting (incidents, MTTR) | By the time these move, the damage already happened — no window to intervene | Pair with leading indicators: PR review latency, CI flake trend, deploy-frequency trend |\n"
        "| \"All green\" dashboard with no thresholds shown | Reader can't tell if green means elite or merely \"not on fire\" | Always show the band/threshold next to every number |\n"
        "| Cherry-picking the best repo in a multi-repo rollup | Conceals which teams actually need help; defeats the purpose of an accountability signal | Report every configured repo, including the ones that look bad |\n"
        "| Deploy frequency alone read as \"velocity\" | Goodhart risk: deploy count can be inflated with no-op or artificially split deploys | Always pair with change-failure rate and lead time — the four keys are meant to be read together |\n"
        "\n"
        "### Worked example\n"
        "- **Weak:** \"Our engineering health score is 82/100, we're doing great.\"\n"
        "- **Sharp:** \"On the four DORA keys: deploy frequency is High (daily-to-weekly), lead time is Elite "
        "(<1 day), but change-failure rate is Low (46–60%, i.e. under half of deploys need a follow-up fix) and "
        "MTTR is Medium (1 day–1 week). A single blended score would have averaged the great lead time against the "
        "bad failure rate and reported 'fine' — the actual finding is we ship fast but too much of what we ship "
        "breaks, and it takes too long to notice. That's a review/test-quality problem, not a throughput problem. "
        "The leading indicator worth watching is PR review latency, which has been trending up over the last 4 "
        "weeks — consistent with rushed reviews driving the failure rate.\"\n"
        "- The sharp version names the concealed axis (failure rate hidden by a blended score), cites the evidence "
        "(the band table plus the trending leading indicator), and points at the actual fix (review quality, not "
        "\"go faster\").\n"
        "\n"
        "### What this skill must not do\n"
        "- Not invent metric values when an integration is unavailable or unhealthy — say so and point to setup/"
        "doctor rather than fabricate a number.\n"
        "- Not compare or rank individual engineers — team/repo level only.\n"
        "- Not substitute for an incident postmortem — this surfaces trend and risk, not the root cause of one "
        "specific event.\n"
        "- Not report on repos the user/config didn't specify."
    ),
    "engineering/silo-scan": (
        "## Domain rules — silo / bus-factor scan\n"
        "\n"
        "### Absolute rules\n"
        "1. Bus factor is the minimum number of people whose sudden unavailability would critically stall a "
        "module or codebase. Measure it from commit and review authorship over a **trailing window (6-12 months)**, "
        "never all-time history, which dilutes current risk with a departed contributor's old commits.\n"
        "2. Report bus factor and silo ratio **per critical module/directory**, not repo-wide only. A healthy-"
        "looking repo aggregate can still hide a single-owner critical module inside it.\n"
        "3. A single-owner module is a risk even when the code is well-written. Code quality and knowledge "
        "concentration are independent axes — good code with one owner still stalls onboarding, review depth, and "
        "incident response when that person is unavailable.\n"
        "4. Measure **review-authorship spread** independently from commit-authorship spread. A module can look "
        "fine on who wrote the code while every review was rubber-stamped by the same single approver, meaning no "
        "one else has actually vetted the logic even by proxy.\n"
        "5. Weight remediation priority by **change frequency and downstream dependents (fan-in)**, not ownership "
        "concentration alone. A single-owner module that rarely changes and has no callers is a lower priority than "
        "a single-owner module that changes weekly and six services depend on.\n"
        "6. Frame every finding as organizational/process risk (cross-training, pairing, documentation gap) — "
        "never as a judgment on the individual (\"this person hoards knowledge\"). Naming a name as the finding "
        "discourages the transparency the scan depends on.\n"
        "\n"
        "### Thresholds\n"
        "| Signal | Threshold | Why |\n"
        "|---|---|---|\n"
        "| Bus factor on a critical module | ≤2 = high risk | Roughly 65% of studied popular GitHub projects have a bus factor ≤2, and under 10% exceed 10 — a bus factor of 1-2 is common, not exceptional, but still a named risk on anything critical ([truck-factor study, arXiv](https://arxiv.org/pdf/2202.01523)). |\n"
        "| Silo ratio (top contributor's share of meaningful commits) | >70% over trailing 6 months on a critical module | Meaningful excludes formatting/auto-generated diffs; above this, the module is effectively single-authored regardless of nominal team size. |\n"
        "| Review-participation spread | <2 distinct approvers merging to a critical module over trailing 90 days | A review-silo flag independent of the commit-authorship number — approval spread and authorship spread must both be checked. |\n"
        "| Remediation priority | top-quartile change frequency **and** silo ratio >70% **and** fan-in ≥1 dependent service | Combine concentration with churn and blast radius before prioritizing — a static, low-dependency file doesn't need the same urgency. |\n"
        "| Onboarding lag | new team member's first unassisted merged change to an owned module >60 days after joining | A concrete signal that knowledge transfer for that module hasn't happened yet. |\n"
        "\n"
        "### Named anti-patterns\n"
        "| Anti-pattern | Why wrong | What instead |\n"
        "|---|---|---|\n"
        "| Repo-wide bus factor only | A healthy-looking aggregate can hide a single-owner critical module | Report bus factor per critical module/directory, not just the repo aggregate |\n"
        "| Silo flag as individual indictment | Frames a systemic gap as a personal failing; discourages transparency and pushes experts to hide rather than share knowledge | Frame as organizational risk: \"module X has one reviewer; recommend pairing/rotation,\" never \"Y hoards knowledge\" |\n"
        "| Ignoring review-authorship concentration | A module can look fine on commit spread while every review is rubber-stamped by the same approver | Measure commit-authorship and review-authorship spread independently |\n"
        "| Flagging every single-owner module equally | Wastes remediation effort on low-churn, low-blast-radius files | Weight by change frequency and fan-in before prioritizing |\n"
        "| Using all-time git history | Dilutes a departed contributor's old commits into current risk, understating who actually owns the module today | Use a trailing 6-12 month window for the ownership calculation |\n"
        "\n"
        "### Worked example\n"
        "- **Weak:** \"This module was written by one person, that's risky.\"\n"
        "- **Sharp:** \"`billing/src/proration.ts` has a silo ratio of 91% (one author, trailing 6 months, "
        "excluding formatting-only commits) and is in the top decile for change frequency this quarter (14 merges), "
        "with 6 downstream callers. Independently, review participation over the same window shows only 1 distinct "
        "approver across all 14 merges — the concentration exists on both the write side and the review side, so "
        "no one else has verified the logic even by proxy. This is a high-priority pairing target given the churn "
        "and fan-in, not a low-churn file we can defer. Recommend the second reviewer on the next 3 merges be "
        "someone new to the module specifically to build a second capable reviewer, not to rubber-stamp.\"\n"
        "- The sharp version names the mechanism (write-side and review-side concentration are independent "
        "findings), the evidence (silo ratio, churn rank, fan-in, reviewer count), and the fix (targeted pairing, "
        "sized to the actual risk).\n"
        "\n"
        "### What this skill must not do\n"
        "- Not a performance-review or individual-accountability tool — never produce a name-and-shame ranking.\n"
        "- Not a substitute for actual documentation — surfacing a gap doesn't close it; hand off remediation "
        "(pairing schedule, doc sprint) as a recommendation, not an automatic assignment.\n"
        "- Not repo-wide-only reporting — findings must resolve to specific modules/directories to be actionable.\n"
        "- Not based on all-time git blame alone — must use a bounded, recent window."
    ),
    "metrics/team-metrics": (
        "## Domain rules — team metrics\n"
        "\n"
        "### Absolute rules\n"
        "1. Goodhart's Law governs every metric here: once a number becomes a target, people optimize the number, "
        "not the goal it was meant to represent. Name this explicitly whenever a metric is proposed as a target "
        "rather than a diagnostic signal.\n"
        "2. Velocity and story points measure **estimated effort**, not delivered value or productivity. They are "
        "team-relative and un-normalized by design — comparing velocity across teams, or using it to judge "
        "individual output, is a category error, not just a bad practice "
        "([Fowler: \"velocity is not a measure of productivity\"](https://www.artisanagility.com/blog/velocity-is-not-a-productivity-metric-and-never-was)).\n"
        "3. Report flow metrics with their real definitions, not colloquial synonyms: **cycle time** is time-in-"
        "process for one item; **throughput** is items completed per unit time; **WIP** is items currently in "
        "progress; **flow efficiency** is active time divided by total elapsed time.\n"
        "4. Apply **Little's Law** — WIP = throughput × cycle time — as a consistency check, not three independently "
        "estimated numbers. If reported WIP, throughput, and cycle time don't roughly satisfy the identity, one "
        "measurement is wrong or the system isn't in a steady state; say which is suspect.\n"
        "5. Report **percentiles (p50/p85 or p95), never a bare average**, for cycle time or any right-skewed "
        "duration metric. An average is dragged toward the fast bulk of the distribution and hides the long tail "
        "that actually generates complaints — the same failure mode as reporting mean latency instead of p95/p99.\n"
        "6. Never state a rate or percentage without its denominator visible in the same sentence. An unstated-"
        "denominator claim (\"80% of PRs reviewed within a day\") can be true and misleading simultaneously if the "
        "sample, window, or exclusions aren't named alongside it.\n"
        "7. Never compare individuals by these metrics. Team/flow-level only, and always paired with a quality "
        "signal (e.g. change-failure rate alongside throughput) so speed alone isn't read as the whole story.\n"
        "\n"
        "### Thresholds\n"
        "| Signal | Threshold | Why |\n"
        "|---|---|---|\n"
        "| Little's Law identity | WIP ≈ throughput × cycle time | If reported numbers don't roughly satisfy this, flag which measurement is likely wrong or the window isn't steady-state. |\n"
        "| Flow efficiency | typical unmanaged team: 15–40%; high-performing: 40–60% | Most elapsed time in an unmanaged flow is waiting (review queues, handoffs, approvals), not active work — 100% is neither realistic nor the goal ([Swarmia](https://www.swarmia.com/blog/flow-efficiency/)). |\n"
        "| Cycle-time reporting | report p50 **and** p85/p95 together, never a bare average | Duration distributions are right-skewed; the mean sits far from the typical case and hides the tail. |\n"
        "| Velocity comparison across teams | never valid (0 tolerance) | Story points aren't normalized across teams or estimators; a cross-team velocity comparison compares nothing meaningful. |\n"
        "| Denominator disclosure | 100% of published rate/percentage metrics state N and window in the same sentence/caption | Without it, the number can't be evaluated for whether it's meaningful or cherry-picked. |\n"
        "| WIP per person | practitioner guideline: 1-2 active items | Above this, context-switching cost and Little's Law both predict rising cycle time even with constant throughput. |\n"
        "\n"
        "### Named anti-patterns\n"
        "| Anti-pattern | Why wrong | What instead |\n"
        "|---|---|---|\n"
        "| Velocity as a productivity KPI | Goodhart's Law: teams inflate point estimates once velocity is tracked as a target | Track flow metrics (cycle time, throughput) instead; keep velocity internal to the originating team's own sprint planning |\n"
        "| Reporting average cycle time only | Right-skewed distributions make the mean dragged and unrepresentative — same shape problem as mean vs. p99 latency | Report percentiles (p50 + p85/p95) side by side |\n"
        "| Unstated-denominator rate (\"80% shipped on time\") | True and misleading simultaneously if N, window, or exclusions aren't stated | State N, window, and inclusion criteria in the same sentence |\n"
        "| Comparing individual engineers by ticket count/velocity | Goodhart at the person level, plus tickets/points vary wildly in size and aren't comparable across people | Report team/flow-level only; use qualitative review, not a ticket count, for individual signal |\n"
        "| Treating WIP, throughput, and cycle time as three independent facts | They're linked by Little's Law; reporting them without the identity misses an internal-consistency check and an obvious lever | Apply WIP = throughput × cycle time explicitly; recommend a WIP limit when cycle time is the actual complaint |\n"
        "\n"
        "### Worked example\n"
        "- **Weak:** \"Team velocity is up 20% this quarter, we're getting more productive.\"\n"
        "- **Sharp:** \"Story points completed per sprint rose ~20%, but average points-per-ticket also rose (5 "
        "points vs. 3 last quarter) — consistent with estimate inflation, a known Goodhart response once velocity "
        "started appearing in the quarterly review deck. The flow metrics tell a different story: median (p50) "
        "cycle time held flat at 3 days, but p85 cycle time rose from 6 to 11 days — a growing share of work is "
        "stuck in a long tail, mostly PRs waiting >48h for a second reviewer. Recommend dropping velocity from the "
        "quarterly deck and tracking p50/p85 cycle time plus WIP (currently ~2.4 items/engineer, above the 1-2 "
        "guideline) instead — capping WIP is the direct lever on the actual complaint (things take a long time to "
        "land), not a velocity target the numbers show is already being gamed.\"\n"
        "- The sharp version names the mechanism (estimate inflation under Goodhart's Law), the evidence (points-"
        "per-ticket drift, p50 vs. p85 divergence, WIP above guideline), and the fix (swap the tracked metric, cap "
        "WIP).\n"
        "\n"
        "### What this skill must not do\n"
        "- Not a performance-review or individual-ranking tool — team/flow-level only, ever.\n"
        "- Not invent org-specific velocity or story-point history — derive only from configured Jira/GitHub data, "
        "and label gaps rather than fill them.\n"
        "- Not a substitute for qualitative signal (interviews, retro themes) when the question is \"why,\" not "
        "just \"what changed.\"\n"
        "- Not present any rate or percentage without its denominator in the same sentence."
    ),
}
